#!/usr/bin/with-contenv bash
# vim:set ft=sh sw=2 sts=2 ts=2 et:

APP_UID=${APP_UID:-1000}
APP_GID=${APP_GID:-1000}
APP_GUEST_CFG=${APP_GUEST_CFG:-/config}
APP_USER=${APP_USER:-appuser}

CURR_SID=$(stat -c"%u:%g" "$APP_GUEST_CFG")
if [[ "${CURR_SID}" != "${APP_UID}:${APP_GID}" ]] ; then
  chown -R "$APP_UID":"$APP_GID" "$APP_GUEST_CFG"
fi

if [[ ! -f "${APP_GUEST_CFG}/nzbget.conf" ]]; then
  cp "/usr/lib/${APP_NAME}/nzbget.conf" "${APP_GUEST_CFG}/nzbget.conf"
  chown "${APP_UID}":"${APP_GID}" "${APP_GUEST_CFG}/nzbget.conf"
fi
