#!/usr/bin/with-contenv bash
# vim:set ft=sh sw=2 sts=2 st=2 et:

CONFIG_FILE="/config/nzbget.conf"
APP_PORT=${APP_PORT:-6789}

if [[ -f ${CONFIG_FILE} ]]; then
  sed -i s/"^\(SecurePort[=]\)\([0-9]\+\)"/"\1${APP_PORT}"/ ${CONFIG_FILE}
fi
