#!/usr/bin/with-contenv bash
# vim:set ft=sh sw=2 sts=2 st=2 et:

USER_UID=${USER_UID:-1000}
USER_GID=${USER_GID:-1000}

APP_USER=${APP_USER:-appuser}

# del emby user and group
groupdel -f appuser 2> /dev/null
userdel -f appuser 2> /dev/null

if getent group ${USER_GID} > /dev/null; then
  groupdel -f ${USER_GID} 2> /dev/null
fi

# add USER GID
if ! getent group ${APP_USER} > /dev/null; then
  groupadd -f -g ${USER_GID} ${APP_USER} > /dev/null 2>&1
fi

if getent passwd ${USER_UID} > /dev/null; then
  userdel ${USER_UID} 2> /dev/null
fi

# create user with USER_UID
if ! getent passwd ${APP_USER} > /dev/null; then
  useradd \
    --home-dir /opt/teamviewer/profile \
    --create-home \
    --shell /bin/false \
    --uid ${USER_UID} \
    --gid ${USER_GID} \
    --comment 'Container application user.' ${APP_USER} > /dev/null 2>&1
fi

chown -R ${APP_USER}:${APP_USER} /opt/teamviewer
