#!/usr/bin/with-contenv bash
# vim:set ft=sh sw=2 sts=2 st=2 et:

APP_UID=${APP_UID:-1000}
APP_GID=${APP_GID:-1000}

APP_USER=${APP_USER:-appuser}
APP_CONFIG=${APP_CONFIG:-/config}

ln -s ${APP_CONFIG} /home/${APP_USER}/.weechat
if [[ -z "$(ls -A ${APP_CONFIG})" ]]; then
  echo "Prepping weechat..."
  tar xzf /var/cache/weechat.tgz -C ${APP_CONFIG}
  chown -R ${APP_UID}:${APP_GID} ${APP_CONFIG}
fi
