#!/bin/bash

PATH=/usr/sbin:/usr/bin:/sbin:/bin
# TODO: ensure this gets updated by entrypoint script on install
RDESKTOP_USER=${RDESKTOP_USER:-rdesktop}
RDESKTOP_REPO=${RDESKTOP_REPO:-$USER}
USER_REPO=${RDESKTOP_REPO:-"hurricanehrndz"}

# do we need to use sudo to start docker containers?
( id -Gn | grep -q docker ) || SUDO=sudo

USER_UID=$(id -u)
USER_GID=$(id -g)

XSOCK=/tmp/.X11-unix
XAUTH=/tmp/.docker.xauth

list_commands() {
  echo ""
  echo "Launch rdesktop using:"
  echo "  rdesktop                        - Launch rdesktop"
  echo ""
  exit 1
}

cleanup_stopped_virt_manager_instances() {
  echo "Cleaning up stopped rdesktop instances..."
  for c in $(${SUDO} docker ps -a -q)
  do
    image=$(${SUDO} docker inspect -f {{.Config.Image}} ${c})
    if [[ ${image} == "${USER_REPO}/rdesktop:latest" ]]; then
      running=$(${SUDO} docker inspect -f {{.State.Running}} ${c})
      if [[ ${running} != true ]]; then
        ${SUDO} docker rm -v "${c}" >/dev/null
      fi
    fi
  done
}

prepare_docker_env_parameters() {
  ENV_VARS+=" --env=USER_UID=${USER_UID}"
  ENV_VARS+=" --env=USER_GID=${USER_GID}"
  ENV_VARS+=" --env=DISPLAY"
  ENV_VARS+=" --env=XAUTHORITY=${XAUTH}"
  ENV_VARS+=" --env=TZ=$(cat /etc/timezone)"
  ENV_VARS+=" --env=RDESKTOP_USER=${RDESKTOP_USER}"
}

prepare_docker_volume_parameters() {
  touch ${XAUTH}
  xauth nlist :0 | sed -e 's/^..../ffff/' | xauth -f ${XAUTH} nmerge -

  VOLUMES+=" --volume=${XSOCK}:${XSOCK}"
  VOLUMES+=" --volume=${XAUTH}:${XAUTH}"
}

prog=$(basename $0)
exec=$(which $prog)
if [[ ${prog} == "rdesktop" ]]; then
  [[ "${1}" == "help" ]] && list_commands && exit 1
fi

cleanup_stopped_virt_manager_instances
prepare_docker_env_parameters
prepare_docker_volume_parameters

echo "Starting ${prog}..."
${SUDO} docker run -d \
  ${ENV_VARS} \
  ${VOLUMES} \
  --name="${prog}" \
  --hostname="rdesktop" \
  ${USER_REPO}/rdesktop:latest ${prog} $@ >/dev/null
