#!/usr/bin/with-contenv bash
# vim:set ft=sh sw=4 sts=4 st=4 noet:

APP_UID=${APP_UID:-1000}
APP_GID=${APP_GID:-1000}

APP_USER=${APP_USER:-appuser}
APP_CONFIG=${APP_CONFIG:-/config}

PGDATA=$APP_CONFIG/pgdata

QUASSEL_USER=${QUASSEL_USER:-admin}
QUASSEL_PORT=${QUASSEL_PORT:-4242}

export HOME=/home/${APP_USER}
cd $HOME

s6-applyuidgid -u $APP_UID -g $APP_GID check_ssl

# wait for postgresql to come up
sleep 1
if [ ! -e "/var/run/postgresql/.s.PGSQL.5432" ]; then
	echo "PostgreSQL not up!"
	exit 1
fi

echo "Testing PostgreSQL for Quassel setup..."
QUASSEL_EXIST=$(s6-applyuidgid -u $APP_UID -g $APP_GID psql postgres -tAc "SELECT 1 FROM pg_roles WHERE rolname='quassel';")

if [ ! -n "$QUASSEL_EXIST" ]; then
	echo "Setting up database for quasselcore."
	s6-applyuidgid -u $APP_UID -g $APP_GID psql postgres -c "CREATE USER quassel ENCRYPTED PASSWORD 'password';" > /dev/null 2>&1
	s6-applyuidgid -u $APP_UID -g $APP_GID psql postgres -c "CREATE DATABASE quassel WITH OWNER quassel ENCODING 'UTF8';" > /dev/null 2>&1
	s6-applyuidgid -u $APP_UID -g $APP_GID expect -c "set timeout -1;spawn /usr/bin/quasselcore --configdir=/config --port=$QUASSEL_PORT --select-backend=PostgreSQL --require-ssl; expect \"Username (quassel):\"; send \"\n\";expect \"Password:\"; send \"password\n\"; expect \"Hostname (localhost):\"; send \"\n\"; expect \"Port (5432):\"; send \"\n\"; expect \"Database (quassel):\"; send \"\n\"; expect \"Username:\"; send \"admin\n\";expect \"Password:\"; send \"password\n\"; expect \"Repeat Password:\"; send \"password\n\";expect eof; exit;"
fi

echo "Starting Quassel Core..."
s6-applyuidgid -u $APP_UID -g $APP_GID /usr/bin/quasselcore --configdir=/config --port=$QUASSEL_PORT --require-ssl
