#!/usr/bin/with-contenv bash
# vim:set ft=sh sw=2 sts=2 st=2 et:

USER_UID=${USER_UID:-1000}
USER_GID=${USER_GID:-1000}

APP_USER=${APP_USER:-appuser}

# del appuser from user and group databases
groupdel -f appuser 2> /dev/null
userdel -f appuser 2> /dev/null

if getent group ${USER_GID} > /dev/null; then
  groupdel -f ${USER_GID} 2> /dev/null
fi

# add USER GID
if ! getent group ${APP_USER} > /dev/null; then
  groupadd -f -g ${USER_GID} ${APP_USER} > /dev/null 2>&1
fi

if getent passwd ${USER_UID} > /dev/null; then
  userdel ${USER_UID} 2> /dev/null
fi

# create user with USER_UID
if ! getent passwd ${APP_USER} > /dev/null; then
  useradd \
    --home-dir /home/${APP_USER} \
    --create-home \
    --shell /bin/bash \
    --uid ${USER_UID} \
    --gid ${USER_GID} \
    --comment 'Container application user.' ${APP_USER} > /dev/null 2>&1
fi

# mutt config
if [ -d /home/${APP_USER}/.mutt ]; then
  mkdir -p /home/${APP_USER}/.mutt/temp
  cp -R /var/cache/mutt_config/* /home/${APP_USER}/.mutt
  chown -R ${USER_UID}:${USER_GID} \
  /home/${APP_USER}/.mutt
fi

# gnupg config
if [ -d /home/${APP_USER}/.gnupg ]; then
  chown -R ${USER_UID}:${USER_GID} \
  /home/${APP_USER}/.gnupg
fi

# vim config
mv /var/cache/.vim /home/${APP_USER}/
chown -R ${USER_UID}:${USER_GID} \
  /home/${APP_USER}/.vim

# fix configs permissions
chown ${USER_UID}:${USER_GID} /home/${APP_USER}
