#!/usr/bin/with-contenv bash
# vim:set ft=sh sw=2 sts=2 st=2 et:

APP_UID=${APP_UID:-1000}
APP_GID=${APP_GID:-1000}

APP_USER=${APP_USER:-appuser}
KEEP_TRANSCODE=${KEEP_TRANSCODE:-"false"}

LIBRESONIC_MAX_MEMORY=${MAX_MEM:-150}
LIBRESONIC_HOME=/config
LIBRESONIC_HOST=0.0.0.0
LIBRESONIC_PORT=${HTTP_PORT:-4040}
LIBRESONIC_CONTEXT_PATH=${CONTEXT_PATH:-/}
LIBRESONIC_MAX_MEMORY=${MAX_MEM:-150}
LIBRESONIC_DEFAULT_MUSIC_FOLDER=/music
LIBRESONIC_DEFAULT_PODCAST_FOLDER=/podcasts
LIBRESONIC_DEFAULT_PLAYLIST_FOLDER=/playlists

# Use JAVA_HOME if set, otherwise assume java is in the path.
JAVA=java
if [[ -e "${JAVA_HOME}" ]]
  then
  JAVA=${JAVA_HOME}/bin/java
fi

# Use system install of ffmpeg for transcoding
if [ "$KEEP_TRANSCODE" == "false" ]; then
  [ ! -d $LIBRESONIC_HOME/transcode ] || rm -r $LIBRESONIC_HOME/transcode
  mkdir -p $LIBRESONIC_HOME/transcode
  ln -s "$(command -v ffmpeg)" $LIBRESONIC_HOME/transcode/ffmpeg
fi

if [ -d "${LIBRESONIC_HOME}" ]; then
  CURR_SID=$(stat -c"%u:%g" ${LIBRESONIC_HOME})
  if [ "$CURR_SID" != "$APP_UID:$APP_GID" ] ; then
    chown -R $APP_UID:$APP_GID ${LIBRESONIC_HOME}
  fi
fi

if [ -d "${LIBRESONIC_HOME}/transcode" ]; then
  CURR_SID=$(stat -c"%u:%g" ${LIBRESONIC_HOME}/transcode)
  if [ "$CURR_SID" != "$APP_UID:$APP_GID" ] ; then
    chown -R $APP_UID:$APP_GID ${LIBRESONIC_HOME}/transcode
  fi
fi

cd /opt/libresonic/
echo "Starting Libresonic.."
s6-applyuidgid -u $APP_UID -g $APP_GID ${JAVA} \
  -Xmx${LIBRESONIC_MAX_MEMORY}m \
  -Dserver.host=${LIBRESONIC_HOST} \
  -Dserver.port=${LIBRESONIC_PORT} \
  -Dserver.contextPath=${LIBRESONIC_CONTEXT_PATH} \
  -Dlibresonic.home=${LIBRESONIC_HOME} \
  -Dlibresonic.host=${LIBRESONIC_HOST} \
  -Dlibresonic.port=${LIBRESONIC_PORT} \
  -Dlibresonic.contextPath=${LIBRESONIC_CONTEXT_PATH} \
  -Dlibresonic.defaultMusicFolder=${LIBRESONIC_DEFAULT_MUSIC_FOLDER} \
  -Dlibresonic.defaultPodcastFolder=${LIBRESONIC_DEFAULT_PODCAST_FOLDER} \
  -Dlibresonic.defaultPlaylistFolder=${LIBRESONIC_DEFAULT_PLAYLIST_FOLDER} \
  -Djava.awt.headless=true \
  -jar libresonic.war
