#!/usr/bin/with-contenv bash
# vim:set ft=sh sw=2 sts=2 st=2 et:

APP_UID=${APP_UID:-1000}
APP_GID=${APP_GID:-1000}

APP_USER=${APP_USER:-appuser}
APP_CONFIG=${APP_CONFIG:-/config}

if [[ -f ${APP_CONFIG}/personalization ]]; then
  source ${APP_CONFIG}/personalization
fi

# Create znc config if it doesn't exist
if [[ ! -f "${APP_CONFIG}/configs/znc.conf" ]]; then
  mkdir -p "${APP_CONFIG}/configs"
  cp /var/cache/znc.conf.default "${APP_CONFIG}/configs/znc.conf"

  # setup random password for default admin
  echo "Generating random password..."
  PASS="$(date +%s | sha256sum | base64 | cut -c1-20 | head -1)"
  SALT="$(strings /dev/urandom | grep -o '[A-Za-z0-9,+()]' | head -n 20 | tr -d '\n';echo -n)"
  HASH="$(echo -n "${PASS}${SALT}" | sha256sum | awk '{print $1}')"
  sed -i -e s%"\(\s\+Hash\s\+=\).*"%"\1 ${HASH}"% ${APP_CONFIG}/configs/znc.conf
  sed -i -e s%"\(\s\+Salt\s\+=\).*"%"\1 ${SALT}"% ${APP_CONFIG}/configs/znc.conf
  echo "Password for ${znc_user} is ${PASS}"
  if [[ -n "$znc_user" ]] && [[ -n "$znc_nick" ]] && [[ -n "$znc_name" ]]; then
      echo "Personalizing znc config..."
      sed -i -e s%"\(\s\+AltNick\s\+=\).*"%"\1 ${znc_nick}_"% ${APP_CONFIG}/configs/znc.conf
      sed -i -e s%"\(\s\+Ident\s\+=\).*"%"\1 ${znc_nick}"% ${APP_CONFIG}/configs/znc.conf
      sed -i -e s%"\(\s\+Nick\s\+=\).*"%"\1 ${znc_nick}"% ${APP_CONFIG}/configs/znc.conf
      sed -i -e s%"\(\s\+RealName\s\+=\).*"%"\1 ${znc_name}"% ${APP_CONFIG}/configs/znc.conf
      sed -i -e s%"\(<User\s\).*"%"\1${znc_user}>"% ${APP_CONFIG}/configs/znc.conf
    fi
    chown -R $APP_UID:$APP_GID ${APP_CONFIG}/configs
  fi

if [[ ! -f "${APP_CONFIG}/configs/znc.pem" ]]; then
  znc --makepem -d "$APP_CONFIG/configs"
  chown $APP_UID:$APP_GID $APP_CONFIG/configs/znc.pem
fi
