#!/usr/bin/with-contenv bash
# vim:set ft=sh sw=2 sts=2 st=2 et:

APP_UID=${APP_UID:-1000}
APP_GID=${APP_GID:-1000}

APP_USER=${APP_USER:-appuser}
APP_CONFIG=${APP_CONFIG:-/config}

# Create znc config if it doesn't exist
if [[ ! -f "${APP_CONFIG}/bitlbee/bitlbee.conf" ]]; then
  RANDOM_PASS=$(date +%s | sha256sum | base64 | cut -c1-32 | head -1)
  mkdir -p "${APP_CONFIG}/bitlbee/accounts"
  cp /var/cache/bitlbee.conf.default "${APP_CONFIG}/bitlbee/bitlbee.conf"
  chown -R $APP_UID:$APP_GID ${APP_CONFIG}/bitlbee
  sed -i -e s%"\(AuthPassword\s=\).*"%"\1 ${RANDOM_PASS}"% "${APP_CONFIG}/bitlbee/bitlbee.conf"
  if [[ -f "${APP_CONFIG}/configs/znc.conf" ]]; then
    sed -i -e s%"BITLBEE_PASS"%"${RANDOM_PASS}"% "${APP_CONFIG}/configs/znc.conf"
  fi
fi

mkdir -p /run/bitlbee
chown -R ${APP_UID}:${APP_GID} /run/bitlbee
