#!/bin/bash

PATH=/usr/sbin:/usr/bin:/sbin:/bin
APP_NAME="mutt"
APP_USER=${APP_USER:-appuser}
APP_REPO=${APP_REPO:-hurricane}

# do we need to use sudo to start docker containers?
( id -Gn | grep -q docker ) || SUDO=sudo

USER_UID=$(id -u)
USER_GID=$(id -g)

XSOCK=/tmp/.X11-unix
XAUTH=/tmp/.docker.xauth

list_commands() {
  echo ""
  echo "Launch ${APP_NAME} using:"
  echo "  ${APP_NAME}                        - Launch ${APP_NAME}"
  echo ""
  exit 1
}

cleanup_stopped_instances() {
  echo "Cleaning up stopped ${APP_NAME} instances..."
  for c in $(${SUDO} docker ps -a -q)
  do
    image=$(${SUDO} docker inspect -f {{.Config.Image}} ${c})
    if [[ ${image} == "${APP_REPO}/${APP_NAME}:latest" ]]; then
      running=$(${SUDO} docker inspect -f {{.State.Running}} ${c})
      if [[ ${running} != true ]]; then
        ${SUDO} docker rm -v "${c}" >/dev/null
      fi
    fi
  done
}

prepare_docker_env_parameters() {
  ENV_VARS+=" --env=USER_UID=${USER_UID}"
  ENV_VARS+=" --env=USER_GID=${USER_GID}"
  ENV_VARS+=" --env=TZ=$(cat /etc/timezone)"
  ENV_VARS+=" --env=APP_USER=${APP_USER}"
  ENV_VARS+=" --env=DISPLAY"
  ENV_VARS+=" --env=XAUTHORITY=${XAUTH}"

  if [ ! -z ${GPGKEY} ]; then
    ENV_VARS+=" --env=GPGKEY=${GPGKEY}"
  else
    echo "You need to export your default GPGKEY i.e. export GPGKEY=0x0000."
    exit 1
  fi
}

prepare_docker_volume_parameters() {
  # check to see if secrets exits
  [ ! -f ~/.muttsecrets ] && \
    echo "Error: file .muttsecrets is missing." && \
    exit 1
  VOLUMES+=" --volume=/home/${USER}/.muttsecrets:/home/${APP_USER}/.muttsecrets:ro"

  # check to see if user has gnupg
  [ ! -d ~/.gnupg ] && \
    echo "Please setup GnuPG." && \
    exit 1
  VOLUMES+=" --volume=/home/${USER}/.gnupg/S.gpg-agent:/home/${APP_USER}/.gnupg/S.gpg-agent"
  VOLUMES+=" --volume=/home/${USER}/.gnupg/trustdb.gpg:/home/${APP_USER}/.gnupg/trustdb.gpg"
  VOLUMES+=" --volume=/home/${USER}/.gnupg/pubring.gpg:/home/${APP_USER}/.gnupg/pubring.gpg"

  # make mail directory if it doesn't exist
  [ ! -d ~/.mail ] && \
    echo "Making mail directory." && \
    mkdir -p ~/.mail
  VOLUMES+=" --volume=/home/${USER}/.mail:/home/${APP_USER}/.mail"

  # make mutt directory if it doesn't exist
  [ ! -d ~/.mutt/cache ] && \
    echo "Making mutt cache directory." && \
    mkdir -p ~/.mutt/cache
  VOLUMES+=" --volume=/home/${USER}/.mutt/cache:/home/${APP_USER}/.mutt/cache"

  # make mbsync directory if it doesn't exist
  [ ! -d ~/.mbsync ] && \
    echo "Making isync directory." && \
    mkdir -p ~/.mbsync
  VOLUMES+=" --volume=/home/${USER}/.mbsync:/home/${APP_USER}/.mbsync"
}

prog=$(basename $0)
exec=$(which $prog)
if [[ ${prog} == "${APP_NAME}" ]]; then
  [ "${1}" == "bash" ] && \
    prog=bash && \
    shift
  [[ "${1}" == "help" ]] && \
    list_commands && \
    exit 1
fi

cleanup_stopped_instances
prepare_docker_env_parameters
prepare_docker_volume_parameters

echo "Starting ${prog}..."
${SUDO} docker run -it \
  --rm \
  ${ENV_VARS} \
  ${VOLUMES} \
  --name="${APP_NAME}" \
  ${APP_REPO}/${APP_NAME}:latest ${prog} $@
