#!/usr/bin/with-contenv bash
# vim:set ft=sh sw=2 sts=2 st=2 et:

CONFIG_FILE="/config/sabnzbd.ini"
APP_PORT=${APP_PORT:-8080}
APP_SSL_PORT=${APP_SSL_PORT:-9090}

if [[ -f ${CONFIG_FILE} ]]; then
  sed -i /"^\[misc\]$"/,/"^\[.*$"/s/"^\(port\s\?[=]\s\?\).*"/"\1${APP_PORT}"/ ${CONFIG_FILE}
  sed -i /"^\[misc\]$"/,/"^\[.*$"/s/"^\(https_port\s\?[=]\s\?\).*"/"\1${APP_SSL_PORT}"/ ${CONFIG_FILE}
fi
