#!/usr/bin/with-contenv bash
# vim:set ft=sh sw=2 sts=2 ts=2 et:

APP_UID=${APP_UID:-1000}
APP_GID=${APP_GID:-1000}

APP_USER=${APP_USER:-appuser}

# del appuser from user and group databases
groupdel -f appuser 2> /dev/null
userdel -f appuser 2> /dev/null

if getent group "${APP_GID}" > /dev/null; then
  groupdel -f "${APP_GID}" 2> /dev/null
fi

# add USER GID
if ! getent group "${APP_USER}" > /dev/null; then
  groupadd -f -g "${APP_GID}" "${APP_USER}" > /dev/null 2>&1
fi

if getent passwd "${APP_UID}" > /dev/null; then
  userdel "${APP_UID}" 2> /dev/null
fi

# create user with APP_UID
if ! getent passwd "${APP_USER}" > /dev/null; then
  useradd \
    --home-dir "/home/${APP_USER}" \
    --create-home \
    --shell /bin/bash \
    --uid "${APP_UID}" \
    --gid "${APP_GID}" \
    --comment 'Container application user.' "${APP_USER}" > /dev/null 2>&1
fi

# fix configs permissions
chown "${APP_UID}:${APP_GID}" "/home/${APP_USER}"
