#!/usr/bin/with-contenv bash
# vim:set ft=sh sw=2 sts=2 ts=2 et:

APP_DIR=/opt/${APP_NAME}
APP_UID=${APP_UID:-1000}
APP_GID=${APP_GID:-1000}
APP_USER=${APP_USER:-appuser}

if [[ ${EDGE} -eq 1 ]]; then
  rel_url="http://release.tinymediamanager.org/download.php"
  rel=$(curl -L "$rel_url" | awk /linux.tar/'{gsub("<a href=\"",""); gsub("\".*$",""); print}' || exit 1)
  download_url="http://release.tinymediamanager.org/$rel" || exit 1
  tmm_file="/tmp/tmm.tgz"
  curl -o "$tmm_file" -L "$download_url" || exit 1
  find "${APP_DIR}" \
    -path "${APP_DIR}/cache" -prune \
    -o -path "${APP_DIR}/data" -prune \
    -o -path "${APP_DIR}/backup" -prune \
    -o -path "${APP_DIR}/logs" -prune \
    -o -path "${APP_DIR}/launcher.log" -prune \
    -exec rm -rf {} \+
  tar -xvf "$tmm_file" -C "/opt/${APP_NAME}" || exit 1
  chown -R "${APP_UID}:${APP_GID}" "/opt/${APP_NAME}"
  rm -rf "$tmm_file"
  echo "Update successful!"
fi
