#!/usr/bin/with-contenv bash
# vim:set ft=sh sw=2 sts=2 ts=2 et:

APP_UID=${APP_UID:-1000}
APP_GID=${APP_GID:-1000}
APP_DIR="/opt/${APP_NAME}"
APP_USER=${APP_USER:-appuser}

CURR_SID=$(stat -c"%u:%g" "$APP_DIR")
if [[ "${CURR_SID}" != "${APP_UID}:${APP_GID}" ]] ; then
  chown -R "$APP_UID":"$APP_GID" "$APP_DIR"
fi
