#!/usr/bin/with-contenv bash
# vim:set ft=sh sw=2 sts=2 st=2 et:
#########################################################################
# Shell script for starting Subsonic.  See http://subsonic.org.         #
#                                                                       #
# Adpated for unRAID by Carlos Hernandez <carlos@techbyte.ca>           #
#                                                                       #
#########################################################################
APP_UID=${APP_UID:-1000}
APP_GID=${APP_GID:-1000}

APP_USER=${APP_USER:-appuser}
KEEP_TRANSCODE=${KEEP_TRANSCODE:-"false"}

SUBSONIC_HOME=/subsonic
SUBSONIC_HOST=0.0.0.0
SUBSONIC_PORT=${HTTP_PORT:-4040}
SUBSONIC_HTTPS_PORT=${HTTPS_PORT:-0}
SUBSONIC_CONTEXT_PATH=${CONTEXT_PATH:-"/"}
SUBSONIC_DB=${DB}
SUBSONIC_MAX_MEMORY=${MAX_MEM:-150}
SUBSONIC_DEFAULT_MUSIC_FOLDER=/music
SUBSONIC_DEFAULT_PODCAST_FOLDER=/podcasts
SUBSONIC_DEFAULT_PLAYLIST_FOLDER=/playlists

# Use JAVA_HOME if set, otherwise assume java is in the path.
JAVA=java
if [ -e "${JAVA_HOME}" ]
  then
  JAVA=${JAVA_HOME}/bin/java
fi

# Use system install of ffmpeg for transcoding
if [ "$KEEP_TRANSCODE" == "false" ]; then
  [ ! -d ${SUBSONIC_HOME}/transcode ] || rm -r ${SUBSONIC_HOME}/transcode
  mkdir -p ${SUBSONIC_HOME}/transcode
  ln -s "$(command -v ffmpeg)" ${SUBSONIC_HOME}/transcode/ffmpeg
fi

if [ -d "${SUBSONIC_HOME}/transcode" ]; then
  CURR_SID=$(stat -c"%u:%g" ${SUBSONIC_HOME}/transcode)
  if [ "$CURR_SID" != "$APP_UID:$APP_GID" ] ; then
    chown -R $APP_UID:$APP_GID ${SUBSONIC_HOME}/transcode
  fi
fi

cd /opt/subsonic/
LOG=${SUBSONIC_HOME}/subsonic_sh.log
echo "Starting Subsonic.."
s6-applyuidgid -u $APP_UID -g $APP_GID ${JAVA} \
  -Xmx${SUBSONIC_MAX_MEMORY}m \
  -Dsubsonic.home=${SUBSONIC_HOME} \
  -Dsubsonic.host=${SUBSONIC_HOST} \
  -Dsubsonic.port=${SUBSONIC_PORT} \
  -Dsubsonic.httpsPort=${SUBSONIC_HTTPS_PORT} \
  -Dsubsonic.contextPath=${SUBSONIC_CONTEXT_PATH} \
  -Dsubsonic.db="${SUBSONIC_DB}" \
  -Dsubsonic.defaultMusicFolder=${SUBSONIC_DEFAULT_MUSIC_FOLDER} \
  -Dsubsonic.defaultPodcastFolder=${SUBSONIC_DEFAULT_PODCAST_FOLDER} \
  -Dsubsonic.defaultPlaylistFolder=${SUBSONIC_DEFAULT_PLAYLIST_FOLDER} \
  -Djava.awt.headless=true \
  -Djava.net.preferIPv4Stack=true \
  -verbose:gc \
  -jar subsonic-booter-jar-with-dependencies.jar > ${LOG}
