#!/usr/bin/with-contenv bash
# vim:set ft=sh sw=2 sts=2 ts=2 et:

APP_UID=${APP_UID:-1000}
APP_GID=${APP_GID:-1000}
APP_GUEST_CFG=${APP_GUEST_CFG:-/config}
APP_USER=${APP_USER:-appuser}
APP_DIR="/opt/${APP_NAME}"

CONFIG_DIRS=(
  "$APP_GUEST_CFG/plugins"
  "$APP_GUEST_CFG/db"
  "$APP_GUEST_CFG/logs"
)

for config_dir in "${CONFIG_DIRS[@]}"; do
  if [[ ! -d $config_dir ]]; then
    mkdir -p "$config_dir"
    chown "$APP_UID":"$APP_GID" "$config_dir"
  fi
done

GUEST_USER_DIRS=("$APP_GUEST_CFG"  "$APP_DIR")

for guest_user_dir in "${GUEST_USER_DIRS[@]}"; do
  CURR_SID=$(stat -c"%u:%g" "$guest_user_dir")
  if [[ "${CURR_SID}" != "${APP_UID}:${APP_GID}" ]] ; then
    chown -R "$APP_UID":"$APP_GID" "$guest_user_dir"
  fi
done
