#!/usr/bin/expect

spawn zypper in x11-video-nvidiaG04
expect {
        -re "Choose from above solutions by number or cancel*" {
                send "2\r";
                expect -re "Continue*" {
                        send "y\r"
                        interact
                }
        }
}
