FROM hurricane/stretch
ENV TERM xterm-256color

RUN apt-get update \
 && apt-get install -y \
	ca-certificates \
	elinks \
	git \
	libsasl2-modules \
	lynx \
	vim-nox \
	python \
	python-yaml \
	libpython2.7-stdlib \
	offlineimap \
	msmtp \
	sqlite \
	pinentry-curses \
	python-pip \
	libassuan0 \
	libc6 \
	libcomerr2 \
	libgnutls-deb0-28 \
	libgpg-error0 \
	libgpgme11 \
	libgssapi-krb5-2 \
	libidn11 \
	libk5crypto3 \
	libkrb5-3 \
	libslang2 \
	libnotmuch4 \
	libsasl2-2 \
	libtinfo5 \
	libtokyocabinet9 \
	libnotify-bin \
	notmuch \
	isync \
	cron \
	python-notmuch \
	dbacl \
	aspell \
    python-dev \
	python-setuptools \
	build-essential \
 && rm -rf /var/lib/apt/lists/* \
 && git clone https://github.com/hurricanehrndz/vim /var/cache/.vim \
 && git clone https://github.com/altercation/vim-colors-solarized /var/cache/.vim/bundle/vim-colors-solarized \
 && git clone https://github.com/dbeniamine/vim-mail.git /var/cache/.vim/bundle/vim-mail \
 && git clone https://github.com/teythoon/afew.git /var/cache/afew/ \
 && pip install goobook \
 && cd /var/cache/afew \
 && python setup.py install --prefix=/usr/local/ \
 && apt-get remove --purge -y build-essential python-dev \
 && apt-get --purge autoremove -y \
 && apt-get autoclean -y \
 && rm -rf /var/lib/apt/lists/* /tmp/*

COPY pkgs/ /var/cache/mutt/
COPY scripts/ /var/cache/mutt/
COPY .mutt /var/cache/mutt/.mutt
COPY muttbot /var/cache/muttbot
COPY entrypoint.sh /sbin/entrypoint.sh
COPY .config /var/cache/.config
RUN chmod 755 /sbin/entrypoint.sh \
 && dpkg -i /var/cache/mutt/*.deb

ENTRYPOINT ["/sbin/entrypoint.sh"]
