#!/usr/bin/with-contenv bash
# vim:set ft=sh sw=2 sts=2 st=2 et:

APP_UID=${APP_UID:-1000}
APP_GID=${APP_GID:-1000}
APP_GCONFIG=${APP_GCONFIG:-/config}
APP_USER=${APP_USER:-appuser}

if [[ ${EDGE} -eq 1 ]]; then
  rm -rf /tmp/${APP_NAME}
  mkdir -p /tmp/${APP_NAME}
  curl -sSL http://update.sonarr.tv/v2/master/mono/NzbDrone.master.tar.gz | tar -C /tmp/${APP_NAME} -xz --strip-components=1
  if [[ $? -eq 0 ]]; then
    rm -rf /opt/${APP_NAME}
    mv /tmp/${APP_NAME} /opt
    chown -R ${APP_UID}:${APP_GID} /opt/${APP_NAME}
    echo "Update successful!"
  else
    echo "Update failed!"
  fi
fi

# enable update script
CONFIG_FILE="${APP_GCONFIG}/config.xml"
if [[ -f $CONFIG_FILE ]]; then
  sed -i 's%<UpdateMechanism>.*</UpdateMechanism>%<UpdateMechanism>Script</UpdateMechanism>%' ${CONFIG_FILE}
  sed -i 's%<UpdateScriptPath>.*</UpdateScriptPath>%<UpdateScriptPath>/bin/sonarr-update.sh</UpdateScriptPath>%' ${CONFIG_FILE}
  if [[ $(grep -c "UpdateScriptPath" ${CONFIG_FILE}) -eq 0 ]]; then
    sed -i 's%\(^</Config>$\)%  <UpdateScriptPath>/bin/sonarr-update.sh</UpdateScriptPath>%' ${CONFIG_FILE}
    echo -n "</Config>" >> $CONFIG_FILE
  fi
else
  {
    echo "<Config>"
    echo "  <LogLevel>Info</LogLevel>"
    echo "  <Port>8989</Port>"
    echo "  <UrlBase></UrlBase>"
    echo "  <BindAddress>*</BindAddress>"
    echo "  <SslPort>9898</SslPort>"
    echo "  <EnableSsl>False</EnableSsl>"
    echo "  <AuthenticationMethod>None</AuthenticationMethod>"
    echo "  <Branch>master</Branch>"
    echo "  <LaunchBrowser>True</LaunchBrowser>"
    echo "  <SslCertHash></SslCertHash>"
    echo "  <UpdateMechanism>Script</UpdateMechanism>"
    echo "  <UpdateScriptPath>/bin/sonarr-update.sh</UpdateScriptPath>"
    echo "</Config>"
  } > $CONFIG_FILE
  chown $APP_UID:$APP_GID $CONFIG_FILE
fi
