#!/usr/bin/with-contenv bash
# vim:set ft=sh sw=4 sts=4 st=4 noet:

APP_UID=${APP_UID:-1000}
APP_GID=${APP_GID:-1000}

APP_USER=${APP_USER:-appuser}
APP_CONFIG=${APP_CONFIG:-/config}

PGDATA=$APP_CONFIG/pgdata

echo "Starting postgres..."
s6-applyuidgid -u $APP_UID -g $APP_GID postgres -h 127.0.0.1 -p 5432 -D $PGDATA > /dev/null 2>&1
