#!/usr/bin/with-contenv bash
# vim:set ft=sh sw=4 sts=4 st=4 noet:


APP_CONFIG=${APP_CONFIG:-/config}
PGDATA=$APP_CONFIG/pgdata

if [ ! -d $PGDATA ]; then
	echo "No existing dabase found."
	mkdir -p $PGDATA
	chown postgres:postgres $PGDATA
	# Init postgresql db
	s6-setuidgid postgres initdb -E 'UTF-8' -D $PGDATA > /dev/null 2>&1
	echo "Created new postgres database."
fi
